---
ssh: ascross

package: go
name: Go
version: 1.8.3
architecture: ""
firmware: 2.6.0

config:
  general:
    developer: "The Go Authors"
    website: "https://golang.org/"
    maintainer: "mafredri"
    email: "mafredri+adm@gmail.com"
    depends: []
    conflicts: []
    package: "PACKAGE"
    name: "NAME"
    version: "VERSION"
    architecture: "ARCHITECTURE"
    firmware: "FIRMWARE"
  register:
    symbolic-link:
      /bin:
        - "*"
    boot-priority:
      start-order: 1
      stop-order: 99

case_sensitive: false
runpath:
eprefix: /usr/local/AppCentral/go
root: /usr/local/AppCentral/go/usr/lib/go
files:
  - /usr/local/AppCentral/go/usr/lib/go
exclude:
